#!/usr/bin/perl -w

use lib "..";
use PHAS_PW_Utils qw[ Ask  get_username get_category get_studentnumber get_uid get_homedir];


foreach my $c ( "Ugrad", "Staff", "Other", "Misc", "Grads") {
	my $user = 'bboop';
	my $home  = get_homedir($c, $user);
	
	print "A useable uid for catgory {$c} is {$home}\n";

}