#!/usr/bin/perl -w

use lib "..";
use PHAS_PW_Utils qw[ Ask  get_username get_category get_studentnumber get_uid get_expdate ];

foreach my $c ( qw [System Ugrad Adj-Assoc Faculty Grads Others Postdocs Staff Misc Visitor ]) {

	my $xdate  = get_expdate($c);
	print "A useable expdate for category {$c}	 is {$xdate}\n";
}