#!/usr/bin/perl -w

use lib "..";
use PHAS_PW_Utils qw[ Ask  get_username];
my $prompt = "please enter a string";
my $default = "default";



my $un = get_username("guess");

print "A useable username is {$un}\n";
