#!/usr/bin/perl -w

use lib "..";
use PHAS_PW;
use Carp;

my $ssh_cmd = "/usr/bin/ssh";
my $user = "bboop";
# Get home directory from pwdfile and display the files
    print "Checking home directory....\n";
   $homedir = (getpwnam($user))[7];
PHAS_PW::delete_homedir ($homedir);

