#!/usr/bin/perl -w

use lib "..";
use PHAS_PW_Utils qw[  validate_Pass];


my @tests = ( 'abcde67^&tyytAS', 'esati%%anenIS#10');

foreach my $pass ( @tests ) {
    print "You entered $pass\n";
    validate_Pass($pass, 500);
}
    