#!/usr/bin/perl -w

use lib "..";
use PHAS_PW_Utils qw[ Ask  get_username get_category get_studentnumber get_Pass_from_Terminal validate_Pass];

print "testing PHAS_PW_Utils::get_password \n";

my $pass1 = "";

$pass1  = PHAS_PW_Utils::get_password('1002');


print "in test only:: your pass is $pass1\n"