#!/usr/bin/perl -w

use lib ".";
use PHAS_PW_Utils;
use English  qw( -no_match_vars );
$ENV{PATH}="";

my $username = $ENV{LOGNAME} || $ENV{USER} || getpwuid($UID);

print "user {$username} real uid {$UID}  effective uif {$EUID}\n";

my $curr_pw = get_Pass_from_Terminal("enter current password <", "nohelp")

