#!/usr/bin/perl -w

# use Config::Simple;
use Config::Tiny;

my $Config = Config::Tiny->new;
$Config = Config::Tiny->read( 'conf.file' );

use Data::Dumper;





foreach my $section (sort keys %$Config) {
    print " \n$section\n";
    my %shash = %{$Config->{$section}};
##print Dumper(%shash);
    foreach my $ckey ( sort keys %shash) {
        print "keys is {$ckey} ==> $shash{$ckey}\n ";
    }
}
my $out = q{$Config->{IPA01}->{'cafile'}};
print "\n\n ca file referenced as $out =>  $Config->{IPA01}->{'cafile'}\n";
