#!/usr/bin/perl

deleteIPA('xx');

sub deleteIPA 
{
use Net::LDAP;

   my $me=shift(@_);

   if ( !$me ) { return 1; }

   # set LDAP configuration options
   my %CONF = (
    "server"     => "ipa.phas.ubc.ca",
    "root_dn"    => "cn=Directory Manager",
    "base_dn"    => "cn=users,cn=compat,dc=phas,dc=ubc,dc=ca",
    "dn_suffix"  => "cn=users,cn=accounts,dc=phas,dc=ubc,dc=ca",
    "obj_class"  => ["posixAccount","top","person","organizationalPerson",
                     "inetOrgPerson","shadowAccount"],
    "cafile"     => '/etc/ldap/cacerts/ipa02.phas.ubc.ca.crt'
              );


print " try connecting to  \n";
print " try connecting to $CONF{server} \n";
   # connect to ldap server
   my $ldap = Net::LDAP->new( $CONF{server}, version => 3 ) or
        die "IPA02 Cannot create new LDAP object - $@";

 	print " connected ...\n";
	exit;
}
